### ISSUE TITLE
TypeError: Can't mix strings and bytes in path components

### ISSUE THREAD

**Issue by YuanXinCherry** [xfanplus/Open-SCPNet#6]
python script/dataset/combine_trainval_sets.py --market1501_im_dir ./Dataset/market1501/images --market1501_partition_file ./Dataset/market1501/partitions.pkl --cuhk03_im_dir ./Dataset/cuhk03/detected/images --cuhk03_partition_file ./Dataset/cuhk03/detected/partitions.pkl --duke_im_dir ./Dataset/duke/images --duke_partition_file ./Dataset/duke/partitions.pkl --save_dir ./Dataset/market1501_cuhk03_duke
Traceback (most recent call last):
  File "script/dataset/combine_trainval_sets.py", line 140, in <module>
    combine_trainval_sets(im_dirs, partition_files, save_dir)
  File "script/dataset/combine_trainval_sets.py", line 59, in combine_trainval_sets
    im_paths = [ospj(im_dir, n) for n in partitions['trainval_im_names']]
  File "script/dataset/combine_trainval_sets.py", line 59, in <listcomp>
    im_paths = [ospj(im_dir, n) for n in partitions['trainval_im_names']]
  File "/home/jy/.conda/envs/reid/lib/python3.6/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/home/jy/.conda/envs/reid/lib/python3.6/genericpath.py", line 151, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components

**Comment by Dtappledoghuati** [comment]
Why not download the provided data set directly？In addition, have you run through this code? I encountered some difficulties.
